// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMGChEZqCShnDAkDeSoCwLrrstiw-85Q',
    appId: '1:374661351492:web:0f6f258a64d7f22c801411',
    messagingSenderId: '374661351492',
    projectId: 'phone-go-974a1',
    authDomain: 'phone-go-974a1.firebaseapp.com',
    storageBucket: 'phone-go-974a1.appspot.com',
    measurementId: 'G-13QREFVF6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKb3utyP-yUDOHoxOVwoqePnF_RaXaqTw',
    appId: '1:374661351492:android:9cdf10eaaf4c745c801411',
    messagingSenderId: '374661351492',
    projectId: 'phone-go-974a1',
    storageBucket: 'phone-go-974a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr2K0nL23icDATUBEmxCAvvpRctenE5bE',
    appId: '1:374661351492:ios:440fb9eb4cfb162f801411',
    messagingSenderId: '374661351492',
    projectId: 'phone-go-974a1',
    storageBucket: 'phone-go-974a1.appspot.com',
    iosClientId: '374661351492-hcjkkngvld1m7o3a7bg57hg3pbav1l8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr2K0nL23icDATUBEmxCAvvpRctenE5bE',
    appId: '1:374661351492:ios:440fb9eb4cfb162f801411',
    messagingSenderId: '374661351492',
    projectId: 'phone-go-974a1',
    storageBucket: 'phone-go-974a1.appspot.com',
    iosClientId: '374661351492-hcjkkngvld1m7o3a7bg57hg3pbav1l8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGMGChEZqCShnDAkDeSoCwLrrstiw-85Q',
    appId: '1:374661351492:web:bb4c679a0fd38353801411',
    messagingSenderId: '374661351492',
    projectId: 'phone-go-974a1',
    authDomain: 'phone-go-974a1.firebaseapp.com',
    storageBucket: 'phone-go-974a1.appspot.com',
    measurementId: 'G-JKXDSVJ2YE',
  );
}
